/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripId = IDL.Nat;
export const CreateTripInput = IDL.Record({
  'totalMiles' : IDL.Float64,
  'dropoffLocation' : IDL.Text,
  'date' : IDL.Text,
  'pickupNumber' : IDL.Text,
  'loadId' : IDL.Text,
  'pickupTime' : IDL.Text,
  'pickupTrailerNumber' : IDL.Text,
  'dropTime' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const TripStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Trip = IDL.Record({
  'id' : TripId,
  'status' : TripStatus,
  'totalMiles' : IDL.Float64,
  'dropoffLocation' : IDL.Text,
  'dateCreated' : Timestamp,
  'date' : IDL.Text,
  'pickupNumber' : IDL.Text,
  'loadId' : IDL.Text,
  'dateCompleted' : IDL.Opt(Timestamp),
  'earnings' : IDL.Float64,
  'pickupTime' : IDL.Text,
  'pickupTrailerNumber' : IDL.Text,
  'dropTime' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const UpdateTripInput = IDL.Record({
  'id' : TripId,
  'totalMiles' : IDL.Opt(IDL.Float64),
  'dropoffLocation' : IDL.Opt(IDL.Text),
  'date' : IDL.Opt(IDL.Text),
  'pickupNumber' : IDL.Opt(IDL.Text),
  'loadId' : IDL.Opt(IDL.Text),
  'pickupTime' : IDL.Opt(IDL.Text),
  'pickupTrailerNumber' : IDL.Opt(IDL.Text),
  'dropTime' : IDL.Opt(IDL.Text),
  'pickupLocation' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'completeTrip' : IDL.Func([TripId], [IDL.Bool], []),
  'createTrip' : IDL.Func([CreateTripInput], [Trip], []),
  'deleteTrip' : IDL.Func([TripId], [IDL.Bool], []),
  'getActiveTrip' : IDL.Func([], [IDL.Opt(Trip)], ['query']),
  'getCompletedTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getTripById' : IDL.Func([TripId], [IDL.Opt(Trip)], ['query']),
  'updateTrip' : IDL.Func([UpdateTripInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripId = IDL.Nat;
  const CreateTripInput = IDL.Record({
    'totalMiles' : IDL.Float64,
    'dropoffLocation' : IDL.Text,
    'date' : IDL.Text,
    'pickupNumber' : IDL.Text,
    'loadId' : IDL.Text,
    'pickupTime' : IDL.Text,
    'pickupTrailerNumber' : IDL.Text,
    'dropTime' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const TripStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Trip = IDL.Record({
    'id' : TripId,
    'status' : TripStatus,
    'totalMiles' : IDL.Float64,
    'dropoffLocation' : IDL.Text,
    'dateCreated' : Timestamp,
    'date' : IDL.Text,
    'pickupNumber' : IDL.Text,
    'loadId' : IDL.Text,
    'dateCompleted' : IDL.Opt(Timestamp),
    'earnings' : IDL.Float64,
    'pickupTime' : IDL.Text,
    'pickupTrailerNumber' : IDL.Text,
    'dropTime' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const UpdateTripInput = IDL.Record({
    'id' : TripId,
    'totalMiles' : IDL.Opt(IDL.Float64),
    'dropoffLocation' : IDL.Opt(IDL.Text),
    'date' : IDL.Opt(IDL.Text),
    'pickupNumber' : IDL.Opt(IDL.Text),
    'loadId' : IDL.Opt(IDL.Text),
    'pickupTime' : IDL.Opt(IDL.Text),
    'pickupTrailerNumber' : IDL.Opt(IDL.Text),
    'dropTime' : IDL.Opt(IDL.Text),
    'pickupLocation' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'completeTrip' : IDL.Func([TripId], [IDL.Bool], []),
    'createTrip' : IDL.Func([CreateTripInput], [Trip], []),
    'deleteTrip' : IDL.Func([TripId], [IDL.Bool], []),
    'getActiveTrip' : IDL.Func([], [IDL.Opt(Trip)], ['query']),
    'getCompletedTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getTripById' : IDL.Func([TripId], [IDL.Opt(Trip)], ['query']),
    'updateTrip' : IDL.Func([UpdateTripInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };