/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateTripInput {
  'totalMiles' : number,
  'dropoffLocation' : string,
  'date' : string,
  'pickupNumber' : string,
  'loadId' : string,
  'pickupTime' : string,
  'pickupTrailerNumber' : string,
  'dropTime' : string,
  'pickupLocation' : string,
}
export type Timestamp = bigint;
export interface Trip {
  'id' : TripId,
  'status' : TripStatus,
  'totalMiles' : number,
  'dropoffLocation' : string,
  'dateCreated' : Timestamp,
  'date' : string,
  'pickupNumber' : string,
  'loadId' : string,
  'dateCompleted' : [] | [Timestamp],
  'earnings' : number,
  'pickupTime' : string,
  'pickupTrailerNumber' : string,
  'dropTime' : string,
  'pickupLocation' : string,
}
export type TripId = bigint;
export type TripStatus = { 'active' : null } |
  { 'completed' : null };
export interface UpdateTripInput {
  'id' : TripId,
  'totalMiles' : [] | [number],
  'dropoffLocation' : [] | [string],
  'date' : [] | [string],
  'pickupNumber' : [] | [string],
  'loadId' : [] | [string],
  'pickupTime' : [] | [string],
  'pickupTrailerNumber' : [] | [string],
  'dropTime' : [] | [string],
  'pickupLocation' : [] | [string],
}
export interface _SERVICE {
  'completeTrip' : ActorMethod<[TripId], boolean>,
  'createTrip' : ActorMethod<[CreateTripInput], Trip>,
  'deleteTrip' : ActorMethod<[TripId], boolean>,
  'getActiveTrip' : ActorMethod<[], [] | [Trip]>,
  'getCompletedTrips' : ActorMethod<[], Array<Trip>>,
  'getTripById' : ActorMethod<[TripId], [] | [Trip]>,
  'updateTrip' : ActorMethod<[UpdateTripInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];