/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateTripInput {
    id: TripId;
    totalMiles?: number;
    dropoffLocation?: string;
    date?: string;
    pickupNumber?: string;
    loadId?: string;
    pickupTime?: string;
    pickupTrailerNumber?: string;
    dropTime?: string;
    pickupLocation?: string;
}
export type Timestamp = bigint;
export interface Trip {
    id: TripId;
    status: TripStatus;
    totalMiles: number;
    dropoffLocation: string;
    dateCreated: Timestamp;
    date: string;
    pickupNumber: string;
    loadId: string;
    dateCompleted?: Timestamp;
    earnings: number;
    pickupTime: string;
    pickupTrailerNumber: string;
    dropTime: string;
    pickupLocation: string;
}
export interface CreateTripInput {
    totalMiles: number;
    dropoffLocation: string;
    date: string;
    pickupNumber: string;
    loadId: string;
    pickupTime: string;
    pickupTrailerNumber: string;
    dropTime: string;
    pickupLocation: string;
}
export type TripId = bigint;
export enum TripStatus {
    active = "active",
    completed = "completed"
}
export interface backendInterface {
    completeTrip(id: TripId): Promise<boolean>;
    createTrip(input: CreateTripInput): Promise<Trip>;
    deleteTrip(id: TripId): Promise<boolean>;
    getActiveTrip(): Promise<Trip | null>;
    getCompletedTrips(): Promise<Array<Trip>>;
    getTripById(id: TripId): Promise<Trip | null>;
    updateTrip(input: UpdateTripInput): Promise<boolean>;
}
import type { Timestamp as _Timestamp, Trip as _Trip, TripId as _TripId, TripStatus as _TripStatus, UpdateTripInput as _UpdateTripInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeTrip(arg0: TripId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTrip(arg0);
            return result;
        }
    }
    async createTrip(arg0: CreateTripInput): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0);
                return from_candid_Trip_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0);
            return from_candid_Trip_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTrip(arg0: TripId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getActiveTrip(): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTrip();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTrip();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedTrips();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedTrips();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripById(arg0: TripId): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrip(arg0: UpdateTripInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(to_candid_UpdateTripInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(to_candid_UpdateTripInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_TripStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TripId;
    status: _TripStatus;
    totalMiles: number;
    dropoffLocation: string;
    dateCreated: _Timestamp;
    date: string;
    pickupNumber: string;
    loadId: string;
    dateCompleted: [] | [_Timestamp];
    earnings: number;
    pickupTime: string;
    pickupTrailerNumber: string;
    dropTime: string;
    pickupLocation: string;
}): {
    id: TripId;
    status: TripStatus;
    totalMiles: number;
    dropoffLocation: string;
    dateCreated: Timestamp;
    date: string;
    pickupNumber: string;
    loadId: string;
    dateCompleted?: Timestamp;
    earnings: number;
    pickupTime: string;
    pickupTrailerNumber: string;
    dropTime: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_TripStatus_n3(_uploadFile, _downloadFile, value.status),
        totalMiles: value.totalMiles,
        dropoffLocation: value.dropoffLocation,
        dateCreated: value.dateCreated,
        date: value.date,
        pickupNumber: value.pickupNumber,
        loadId: value.loadId,
        dateCompleted: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.dateCompleted)),
        earnings: value.earnings,
        pickupTime: value.pickupTime,
        pickupTrailerNumber: value.pickupTrailerNumber,
        dropTime: value.dropTime,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): TripStatus {
    return "active" in value ? TripStatus.active : "completed" in value ? TripStatus.completed : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n1(_uploadFile, _downloadFile, x));
}
function to_candid_UpdateTripInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTripInput): _UpdateTripInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TripId;
    totalMiles?: number;
    dropoffLocation?: string;
    date?: string;
    pickupNumber?: string;
    loadId?: string;
    pickupTime?: string;
    pickupTrailerNumber?: string;
    dropTime?: string;
    pickupLocation?: string;
}): {
    id: _TripId;
    totalMiles: [] | [number];
    dropoffLocation: [] | [string];
    date: [] | [string];
    pickupNumber: [] | [string];
    loadId: [] | [string];
    pickupTime: [] | [string];
    pickupTrailerNumber: [] | [string];
    dropTime: [] | [string];
    pickupLocation: [] | [string];
} {
    return {
        id: value.id,
        totalMiles: value.totalMiles ? candid_some(value.totalMiles) : candid_none(),
        dropoffLocation: value.dropoffLocation ? candid_some(value.dropoffLocation) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        pickupNumber: value.pickupNumber ? candid_some(value.pickupNumber) : candid_none(),
        loadId: value.loadId ? candid_some(value.loadId) : candid_none(),
        pickupTime: value.pickupTime ? candid_some(value.pickupTime) : candid_none(),
        pickupTrailerNumber: value.pickupTrailerNumber ? candid_some(value.pickupTrailerNumber) : candid_none(),
        dropTime: value.dropTime ? candid_some(value.dropTime) : candid_none(),
        pickupLocation: value.pickupLocation ? candid_some(value.pickupLocation) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
